export const CPU_RULES = {
  LYNCH: {
    NORMAL: [
      "CERT_BLACK",
      "FOX_HIT",
      "SPLIT_MEDIUM_ON",
      "HALF_BLACK_HIGH",
      "HALF_BLACK_FLAT",
      "HALF_BLACK_LOW",
      "SPLIT_MEDIUM_OFF",
      "GRAY",
      "HALF_WHITE_LOW",
      "HALF_WHITE_FLAT",
      "HALF_WHITE_HIGH",
      "CERT_WHITE",
    ],

    FOX_ALIVE_WITH_BLACK_RESERVE: [
      "FOX_HIT",
      "CERT_BLACK",
      "SPLIT_MEDIUM_ON",
      "HALF_BLACK_HIGH",
      "HALF_BLACK_FLAT",
      "HALF_BLACK_LOW",
      "SPLIT_MEDIUM_OFF",
      "GRAY",
      "HALF_WHITE_LOW",
      "HALF_WHITE_FLAT",
      "HALF_WHITE_HIGH",
      "CERT_WHITE",
    ],

    FOX_ALIVE_NO_BLACK_RESERVE: [
      "FOX_HIT",
      "GRAY",
      "SPLIT_MEDIUM_ON",
      "HALF_BLACK_HIGH",
      "HALF_BLACK_FLAT",
      "HALF_BLACK_LOW",
      "SPLIT_MEDIUM_OFF",
      "HALF_WHITE_LOW",
      "HALF_WHITE_FLAT",
      "HALF_WHITE_HIGH",
      "CERT_WHITE",
      "CERT_BLACK",
    ],
  },

  RESERVE: {
    NORMAL: [
      "FOX_HIT",
      "HALF_BLACK",
      "GRAY",
      "HALF_WHITE",
      "CERT_WHITE",
    ],

    FOX_ALIVE: [
      "FOX_HIT",
      "GRAY",
      "HALF_BLACK",
      "HALF_WHITE",
      "CERT_WHITE",
    ],
  },

  BITE: {
    FOX_ALIVE: [
      "MEDIUM",
      "CERT_WHITE",
      "HALF_WHITE",
      "GRAY",
      "HALF_BLACK",
      "BLACK",
      "SEER_LOW",
      "SEER_FLAT",
      "SEER_HIGH",
      "FOX",
    ],

    SPLIT_MEDIUM: [
      "MEDIUM",
      "SEER_FLAT",
      "SEER_HIGH",
      "SEER_LOW",
      "CERT_WHITE",
      "HALF_WHITE",
      "GRAY",
      "HALF_BLACK",
      "BLACK",
      "FOX",
    ],

    HIGH_SEER: [
      "SEER_HIGH",
      "MEDIUM",
      "SEER_FLAT",
      "SEER_LOW",
      "CERT_WHITE",
      "HALF_WHITE",
      "GRAY",
      "HALF_BLACK",
      "BLACK",
      "FOX",
    ],

    NORMAL_A: [
      "MEDIUM",
      "SEER_FLAT",
      "SEER_HIGH",
      "SEER_LOW",
      "CERT_WHITE",
      "HALF_WHITE",
      "GRAY",
      "HALF_BLACK",
      "BLACK",
      "FOX",
    ],

    NORMAL_B: [
      "SEER_FLAT",
      "MEDIUM",
      "SEER_HIGH",
      "SEER_LOW",
      "CERT_WHITE",
      "HALF_WHITE",
      "GRAY",
      "HALF_BLACK",
      "BLACK",
      "FOX",
    ],
  },

  GUARD: {
    SPLIT_MEDIUM: [
      "MEDIUM",
      "SEER_FLAT",
      "SEER_HIGH",
      "SEER_LOW",
      "CERT_WHITE",
      "HALF_WHITE",
      "GRAY",
      "HALF_BLACK",
      "BLACK",
      "FOX",
    ],

    HIGH_SEER: [
      "SEER_HIGH",
      "MEDIUM",
      "SEER_FLAT",
      "SEER_LOW",
      "CERT_WHITE",
      "HALF_WHITE",
      "GRAY",
      "HALF_BLACK",
      "BLACK",
      "FOX",
    ],

    NORMAL_A: [
      "MEDIUM",
      "SEER_FLAT",
      "SEER_HIGH",
      "SEER_LOW",
      "CERT_WHITE",
      "HALF_WHITE",
      "GRAY",
      "HALF_BLACK",
      "BLACK",
      "FOX",
    ],

    NORMAL_B: [
      "SEER_FLAT",
      "MEDIUM",
      "SEER_HIGH",
      "SEER_LOW",
      "CERT_WHITE",
      "HALF_WHITE",
      "GRAY",
      "HALF_BLACK",
      "BLACK",
      "FOX",
    ],
  },
};
