export const CPU_RULES = {
  LYNCH: {
    priority: [
      "CERT_BLACK",
      "SPLIT_MEDIUM_ON",
      "HALF_BLACK_HIGH",
      "HALF_BLACK_FLAT",
      "HALF_BLACK_LOW",
      "SPLIT_MEDIUM_OFF",
      "GRAY",
      "HALF_WHITE_LOW",
      "HALF_WHITE_FLAT",
      "HALF_WHITE_HIGH",
      "CERT_WHITE",
    ],
  },

  RESERVE: {
    priority: [
      "HALF_BLACK",
      "GRAY",
      "HALF_WHITE",
      "CERT_WHITE",
    ],
  },

  BITE: {
    pattern: {
      SPLIT_MEDIUM: [
        "MEDIUM",
        "SEER_FLAT",
        "SEER_HIGH",
        "SEER_LOW",
        "CERT_WHITE",
        "HALF_WHITE",
        "GRAY",
        "HALF_BLACK",
        "BLACK",
      ],
      HIGH_SEER: [
        "SEER_HIGH",
        "MEDIUM",
        "SEER_FLAT",
        "SEER_LOW",
        "CERT_WHITE",
        "HALF_WHITE",
        "GRAY",
        "HALF_BLACK",
        "BLACK",
      ],
      NORMAL_A: [
        "MEDIUM",
        "SEER_FLAT",
        "SEER_HIGH",
        "SEER_LOW",
        "CERT_WHITE",
        "HALF_WHITE",
        "GRAY",
        "HALF_BLACK",
        "BLACK",
      ],
      NORMAL_B: [
        "SEER_FLAT",
        "MEDIUM",
        "SEER_HIGH",
        "SEER_LOW",
        "CERT_WHITE",
        "HALF_WHITE",
        "GRAY",
        "HALF_BLACK",
        "BLACK",
      ],
    },
  },

  GUARD: {
    pattern: {
      SPLIT_MEDIUM: [
        "MEDIUM",
        "SEER_FLAT",
        "SEER_HIGH",
        "SEER_LOW",
        "CERT_WHITE",
        "HALF_WHITE",
        "GRAY",
        "HALF_BLACK",
        "BLACK",
      ],
      HIGH_SEER: [
        "SEER_HIGH",
        "MEDIUM",
        "SEER_FLAT",
        "SEER_LOW",
        "CERT_WHITE",
        "HALF_WHITE",
        "GRAY",
        "HALF_BLACK",
        "BLACK",
      ],
      NORMAL_A: [
        "MEDIUM",
        "SEER_FLAT",
        "SEER_HIGH",
        "SEER_LOW",
        "CERT_WHITE",
        "HALF_WHITE",
        "GRAY",
        "HALF_BLACK",
        "BLACK",
      ],
      NORMAL_B: [
        "SEER_FLAT",
        "MEDIUM",
        "SEER_HIGH",
        "SEER_LOW",
        "CERT_WHITE",
        "HALF_WHITE",
        "GRAY",
        "HALF_BLACK",
        "BLACK",
      ],
    },
  },
};
