export {
  makeNewGame,
  logPush,
  getOpponentId,
  getLynchTargetId,
  getReserveTargetId,
  getGuardTargetId,
  getBiteTargetId,
  canAbsentOk,
  doAbsentOkWrapped as doAbsentOk,
  isHumanTurn,
  cpuDoOneImmediateWrapped as cpuDoOneImmediate,
  runAutoUntilHumanTurn,
  applyHumanPick,
  phaseLabel,
} from "./duel/duelGame.js";
